services:
  - type: web
    name: probepaket-finder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_CREDENTIALS_JSON
        value: "PASTE_YOUR_CREDENTIALS_JSON_HERE"
      - key: SPREADSHEET_ID
        value: "191RsU9uDyRQDIM4UITTY2F8KxalA9uGP497pdWKoRvA"
